require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'log/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb
    - app/controllers/**/*.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb

