AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Metrics:
  Exclude:
    - bin/**
    - db/schema.rb
    - db/migrate/**.rb
