inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - db/schema.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/**.rb
