AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics/LineLength:
  Max: 120
  Exclude:
    - bin/bundle

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb
    - app/controllers/**/*.rb

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
    - db/schema.rb

Metrics:
  Exclude:
    - bin/**
    - db/schema.rb
    - db/migrate/**.rb
